In [1]:
#Reading data
import pandas as pd
#Fixings warnings
import warnings 
warnings.filterwarnings('ignore')
#For mathematical operations
import numpy as np
#Visualisation
import seaborn as sns 
import plotly.express as px
from termcolor import colored
import matplotlib.pyplot as plt 
import plotly.graph_objects as go
import plotly.figure_factory as ff

In [3]:
#Data spliting
from sklearn.model_selection import train_test_split

import pandas as pd
# Membaca dataset
data_diabetes = pd.read_csv('diabetes.csv')

# Menampilkan 5 baris pertama dengan gaya tampilan yang telah ditetapkan
styled_data = data_diabetes.head().style.set_properties(**{'background-color': '#538392',
                                                        'color': '#E2EEF3'})
styled_data